service: cmpe-272-serverless-assignment
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
    - httpApi:
        path: /
        method: get
  ImgResize:
    handler: handler.ImageResize
    events:
    - httpApi:
        path: /imageResize
        method: get